---
ID: "a76670a8-797b-4c59-87f6-e6f9c0e4b3b7"
Parent: "1370328b-6793-45ea-8af7-5c0ccc2712ce"
Template: "1370328b-6793-45ea-8af7-5c0ccc2712ce"
Path: "/sitecore/templates/Project/industry-verticals/EventsPage/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C14B6289-8AC2-439C-9E5B-40DE9F820C3F}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ca929f83-c0c2-4c8e-bfa7-42345dfeea3a"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250820T091612Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "35b82a89-814e-4ce7-b0c5-c7a86e91054a"
    - ID: "ad410835-8c75-4179-bfe5-722ebe6bde5c"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mick.wingert@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260401T010123Z
