---
ID: "7ef0f642-4eeb-45bb-b323-be3c0a678394"
Parent: "64c05410-4cfa-4472-abf9-7cbbbc7399cf"
Template: "64c05410-4cfa-4472-abf9-7cbbbc7399cf"
Path: "/sitecore/templates/Project/industry-verticals/Rendering Parameters/Event Details Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c44533f1-4a7c-41ac-99b0-b889d572d62f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mick.wingert@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260401T005209Z
